### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by CoFix** [havenprotocol/haven#10]
Hello Staff,

I am getting this error. How can i fix it?

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libboost_chrono.a(chrono.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libboost_chrono.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/wallet/CMakeFiles/wallet_rpc_server.dir/build.make:130: recipe for target 'bin/haven-wallet-rpc' failed
make[3]: *** [bin/haven-wallet-rpc] Error 1
make[3]: Leaving directory '/home/haven/haven/build/release'
CMakeFiles/Makefile2:2214: recipe for target 'src/wallet/CMakeFiles/wallet_rpc_server.dir/all' failed
make[2]: *** [src/wallet/CMakeFiles/wallet_rpc_server.dir/all] Error 2
make[2]: Leaving directory '/home/haven/haven/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/haven/haven/build/release'
Makefile:68: recipe for target 'release-static' failed
make: *** [release-static] Error 2

**Comment by havenprotocol** [comment]
Hello, 

You need to do what it says and recompile boost with -fPIC.
Afterwards you will likely have to recompile a few other dependencies that will fail with the same error prompting you to recompile them with -FPIC flag.

This is because you are doing a release-static build. If you can get away with a release build you won't run into this.
